project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /src/main/resources/lang/*.json
    translation: /crowdin/lang/%locale%/%original_file_name%
