name: Template Validator

on: 
  issues:
    types: [opened, edited, reopened]

jobs:
  template_validator:
    runs-on: ubuntu-latest
    name: Template Validator
    steps:
    - name: All Checks
      uses: flowdify/contribution-inspector@v1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
